-- MySQL Script generated by MySQL Workbench
-- Qua 23 Mai 2018 14:55:50 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Atividade_JPA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Atividade_JPA` ;

-- -----------------------------------------------------
-- Schema Atividade_JPA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Atividade_JPA` ;
USE `Atividade_JPA` ;

-- -----------------------------------------------------
-- Table `Atividade_JPA`.`Livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Atividade_JPA`.`Livro` ;

CREATE TABLE IF NOT EXISTS `Atividade_JPA`.`Livro` (
  `ISBN` INT NOT NULL,
  `titulo` VARCHAR(1024) NOT NULL,
  `ano` VARCHAR(45) NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Atividade_JPA`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Atividade_JPA`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Atividade_JPA`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `local` VARCHAR(1024) NOT NULL,
  `idade` INT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Atividade_JPA`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Atividade_JPA`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `Atividade_JPA`.`avaliacao` (
  `ISBN` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`ISBN`, `idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
